# Generated by Django 6.0.2 on 2026-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('rollno', models.IntegerField(unique=True)),
                ('department', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('aadarno', models.CharField(max_length=12, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
    ]
